controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home :
    path : /
    controller : App\Controller\CatalogueController::home

categories :
    path : /categories
    controller : App\Controller\CatalogueController::categories

plats :
    path : /plats
    controller : App\Controller\CatalogueController::plats

plats_cat :
    path : /plats/{libelle}
    controller : App\Controller\CatalogueController::plats_cat

profile :
    path : /Connexion_Inscription
    controller : App\Controller\ProfileController::index

register :
    path : /inscription
    controller : App\Controller\RegistrationController::register

login :
    path : /connexion
    controller : App\Controller\SecurityController::login

logout :
    path : /logout
    controller : App\Controller\SecurityController::logout

contact :
    path: /contact
    controller : App\Controller\ContactController::contact