controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home :
    path : /
    controller : App\Controller\CatalogueController::home

categories :
    path : /categories
    controller : App\Controller\CatalogueController::categories

plats :
    path : /plats
    controller : App\Controller\CatalogueController::plats

plats_cat :
    path : /plats/{libelle}
    controller : App\Controller\CatalogueController::plats_cat

profile :
    path : /Connexion_Inscription
    controller : App\Controller\ProfileController::index

profileUser:
    path: /mon-profil
    controller: App\Controller\ProfileController::profileUser
register :
    path : /inscription
    controller : App\Controller\RegistrationController::register

login :
    path : /connexion
    controller : App\Controller\SecurityController::login

logout :
    path : /logout
    controller : App\Controller\SecurityController::logout

contact :
    path: /contact
    controller : App\Controller\ContactController::contact

listPanier :
    path: /panier
    controller: App\Controller\PanierController::listPanier

addPanier :
    path: /panier/ajout/{id}
    controller : App\Controller\PanierController::addPanier

removePanier :
    path : /panier/remove-produit/{id}
    controller: App\Controller\PanierController::removePanier


decreaseQuantity :
    path : /panier/decreaseQuantity/{id}
    controller : App\Controller\PanierController::decreaseQuantity

commande :
    path : /commande
    controller : App\Controller\CommandeController::commande

politique :
    path : /politique-de-confidentialite
    controller : App\Controller\CatalogueController::politique

mentions :
    path : /mentions Legales
    controller : App\Controller\CatalogueController::mentions